# Generated by Django 5.0.4 on 2024-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_app',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='first_app',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
